### ISSUE TITLE
Refine SSN RegEx Pattern (with example)

### ISSUE THREAD

**Issue by oj-codes** [Anas-debug/HIPPAGuard#1]
The existing SSN regex pattern is good enough most of the time but doesn’t validate known invalid ranges. For example, the first three digits of a SSN cannot be 000, 666, or 9xx. So, you should build a pattern that checks for invalid SSN with that criteria. 

Here is an example of a more refined SSN RegEx pattern for SSN: `^(?!000|666|9\d{2})\d{3}-(?!00)\d{2}-(?!0000)\d{4}$`

Explanation:
1. `^(?!000|666|9\d{2})\d{3}-`: The first three digits cannot be 000, 666, or 9xx (which are invalid in real SSNs).
2. `(?!00)\d{2}-`: The next two digits cannot be 00.
3. `(?!0000)\d{4}$`: The last four digits cannot be 0000.

**Comment by Anas-debug** [comment]
@oj-codes Thank you for suggesting this SSN validation enhancement. I've implemented the pattern in PR #2 with comprehensive test coverage ensuring all specified invalid ranges are properly validated.

Please confirm if this implementation aligns with your requirements and if it's appropriate to merge.

**Comment by Anas-debug** [comment]
@oj-codes I've created PR #2 implementing your suggested SSN validation pattern. As the repository owner, I'll proceed with merging since the implementation follows your specified pattern exactly and all tests are passing. Thank you for this security enhancement suggestion.
